### ISSUE TITLE
An API to allow dropping multiple collections(helpful API for testing)

### ISSUE THREAD

**Issue by himank** [tigrisdata/tigris-client-go#226]
The database class has an API to create multiple collections by passing the model,
`CreateCollections(ctx context.Context, model schema.Model, models ...schema.Model) error` 

Similar, to the above, we can have an API to clean up multiple collections. This would be helpful mainly during testing,
`DropCollections(ctx context.Context, model schema.Model, models ...schema.Model) error`

**Comment by efirs** [comment]
There is DropAllCollections added by #219, do we still want to cherry-pick drop?

**Comment by himank** [comment]
Ah, didn't realize that. I think then that should be good for now.
