### ISSUE TITLE
Support secondary index tagging in the model

### ISSUE THREAD

**Issue by efirs** [tigrisdata/tigris-client-go#230]
Index fields can be tagged as:

```
type MyColl1 struct {
  IndexField int `tigris:"index"`
  NestedObj  struct {
     NestedIndexField int `tigris:"index"`
  }
}
```

Generated JSON schema would look like:

```
{
  "title":"my_coll_1",
  "properties":{
    "IndexField":{"type":"integer"},
    "NestedObj":{
      "type":"object",
      "properties": {
        "NestedIndexField":{"type":"integer"}
      },
      "index": ["NestedIndexField"],
    },
  },
  "primary_key":["ID"],
  "index":["IndexField"],
}
```

This follows the specification of ["required" properties](http://json-schema.org/understanding-json-schema/reference/object.html#required-properties) in JSON schema.

**Comment by efirs** [comment]
Later it can be extended to support named, compound indexes:

```
type MyColl1 struct {
  IndexField int `tigris:index:my_index:1`
  NestedObj  struct {
     NestedIndexField int `tigris:index:my_index:2`
  }
}
```

Generated JSON schema would look like:

```
{
  "title":"my_coll_1",
  "properties":{
    "IndexField":{"type":"integer"},
    "NestedObj":{
      "type":"object",
      "properties": {
        "NestedIndexField":{"type":"integer"}
      },
      "indexes": { "my_index" : { "NestedIndexField" : 2 } }
    },
  },
  "primary_key":["ID"],
  "indexes": { "my_index" : { "IndexField" : 1 } }
}
```

**Comment by himank** [comment]
what do you think about having an `index` attribute on the field itself i.e.
`{
  "title":"my_coll_1",
  "properties":{
    "IndexField":{"type":"integer", "index": true},
    "NestedObj":{
      "type":"object",
      "properties": {
        "NestedIndexField":{"type":"integer", "index": true}
      }
    },
  },
  "primary_key":["ID"]
}`

As we will have other attributes on the field itself like `sort`, `unique`, etc

**Comment by ovaistariq** [comment]
- [ ] In the generated json schema what do you think about having index as another property in the field definition. Something like type:integer, index:true

**Comment by efirs** [comment]
Make sense. Updated the diff.
