### ISSUE TITLE
Atomic numeric update operations support in Go Client (increment/decrement/multiply/divide)

### ISSUE THREAD

**Issue by himank** [tigrisdata/tigris-client-go#236]

**Comment by ovaistariq** [comment]
@Shubham8287 Sure, go ahead and take this one :) Yes, please implement similar to TS SDK.

**Comment by efirs** [comment]
@Shubham8287, Right, fields/update.go is where changes should go.
You Just need to add corresponding fields, similar to https://github.com/tigrisdata/tigris-client-go/blob/main/fields/update.go#L31 .
Please mind the json tag here which is what will be marshalled: "$divide" and "$increment" in your example above.
Also corresponding setters should be implemented, similar to: 
[Object scope] https://github.com/tigrisdata/tigris-client-go/blob/main/fields/update.go#L63
[Package scope] https://github.com/tigrisdata/tigris-client-go/blob/main/fields/update.go#L83

**Comment by Shubham8287** [comment]
@Dasio Buddy, not sure what made you work on this but the issue was assigned to me and I was about to raise a PR for this. We should respect basic rules to work on open source just to avoid things like deduplication of efforts.

**Comment by Dasio** [comment]
Sure go ahead, I was just testing Algora. You have started 2 weeks ago and no PR.

I was looking at several issues, and users just assign issues without any work. But yeah you are right.

**Comment by ovaistariq** [comment]
Hi, @Shubham8287 how far along are you with the implementation? If you still need to make progress, then it would be better to let @Dasio proceed with this.

**Comment by Shubham8287** [comment]
I am fine, Let @Dasio go ahead with this.


for @Dasio first of all, I think maintainers should care about timelines, they know the priorities better and Algora should decide about a number of issues at the time not us and rather we should .
> You are just assigning issues to yourself and don't leave anything to others and then even simple issues are blocked for multiple weeks without any good reason.
Not sure, what analysis made you say this. I have 2 other issues assigned to me, One is in review for a long time and the other is pretty big and expected to take time. I have ~3 closed issues, and all of them took about ~2 days (including a task with Tigris as well). though I do not need to justify any of this to you.
I am here to do Engineering and learn, not to argue. Good luck!

Sorry maintainers for spamming here.

**Comment by IoannisFlo** [comment]
hey everyone, this is ioannis, one of the founders at algora. our sincere apologies for everyone's inconvenience here, it's our fault, we'll do a better job of marking in progress and giving status updates. we already updated our bot reply for new bounties, it now asks to use a `/attempt #236` command to notify everyone, and we'll prevent folks from using `/attempt` in multiple bounties of the same org. this is all new and we appreciate your input and the opportunity to improve the workflow with your feedback, thanks in advance for the understanding

**Comment by ovaistariq** [comment]
@Shubham8287, thanks for the flexibility. We appreciate your contributions and would love to see them continue.

P.S. we do not have any issues with multiple issues being worked on by the same contributor
