### ISSUE TITLE
Add support for pagination in the read API

### ISSUE THREAD

**Issue by ovaistariq** [tigrisdata/tigris-client-go#269]
This is for the API documented here: https://www.tigrisdata.com/docs/sdkstools/golang/database/query/

**Comment by Shubham8287** [comment]
Hi, Looking to work on it, @ovaistariq as there are no specs. Can I assume pagination functionality should be similar to what we have for typescript? - https://www.tigrisdata.com/docs/sdkstools/typescript/database/query/#pagination. Let me know if you are expecting anything different.

**Comment by efirs** [comment]
Hi, @Shubham8287! Pagination API is implemented already.
We just need to put documentation in place. We are sorry for the confusion.
Would you be interested in working on https://github.com/tigrisdata/tigris-client-go/issues/223 instead?
If you decide to work on it, I can provide addition information.
Thanks for you interest in contributing!

**Comment by Shubham8287** [comment]
Sure, Np.

**Comment by ovaistariq** [comment]
Yeah, sorry about that. I will close this and create a new one for docs.
