### ISSUE TITLE
Add Count documents API in client

### ISSUE THREAD

**Issue by himank** [tigrisdata/tigris-client-go#271]
The API must be added on the collection level and accept filters. The syntax can be similar to the below,
`func (c *Collection[T]) Count(ctx context.Context, filter filter.Filter) (int64, error)`

The server-side support is added here: https://github.com/tigrisdata/tigris/pull/1068, which returns `count` in the response and honors the filters if passed to return the count for the matched documents.

**Comment by efirs** [comment]
Fixed by #273
